commented all other ci
Signed-off-by: Akash Jaiswal <akashjaiswal3846@gmail.com>

diff --git a/.github/workflows/test-e2e-gpu.yaml b/.github/workflows/test-e2e-gpu.yaml
--- a/.github/workflows/test-e2e-gpu.yaml
+++ b/.github/workflows/test-e2e-gpu.yaml
@@ -1,69 +1,69 @@
-name: GPU E2E Test
+# name: GPU E2E Test
 
-on:
-  workflow_dispatch:
-jobs:
-  gpu-e2e-test:
-    name: GPU E2E Test
-    runs-on: arc-runner-set
+# on:
+#   workflow_dispatch:
+# jobs:
+#   gpu-e2e-test:
+#     name: GPU E2E Test
+#     runs-on: arc-runner-set
 
-    env:
-      GOPATH: ${{ github.workspace }}/go
+#     env:
+#       GOPATH: ${{ github.workspace }}/go
 
-    defaults:
-      run:
-        working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/trainer
+#     defaults:
+#       run:
+#         working-directory: ${{ env.GOPATH }}/src/github.com/kubeflow/trainer
 
-    strategy:
-      fail-fast: false
-      matrix:
-        kubernetes-version: ["1.33.1"]
+#     strategy:
+#       fail-fast: false
+#       matrix:
+#         kubernetes-version: ["1.33.1"]
 
-    steps:
-      - name: Check out code
-        uses: actions/checkout@v4
-        with:
-          ref: ${{ github.event.pull_request.head.sha }}
-          path: ${{ env.GOPATH }}/src/github.com/kubeflow/trainer
+#     steps:
+#       - name: Check out code
+#         uses: actions/checkout@v4
+#         with:
+#           ref: ${{ github.event.pull_request.head.sha }}
+#           path: ${{ env.GOPATH }}/src/github.com/kubeflow/trainer
 
-      - name: Setup Go
-        uses: actions/setup-go@v5
-        with:
-          go-version-file: ${{ env.GOPATH }}/src/github.com/kubeflow/trainer/go.mod
+#       - name: Setup Go
+#         uses: actions/setup-go@v5
+#         with:
+#           go-version-file: ${{ env.GOPATH }}/src/github.com/kubeflow/trainer/go.mod
 
-      - name: Setup Python
-        uses: actions/setup-python@v5
-        with:
-          python-version: 3.11
+#       - name: Setup Python
+#         uses: actions/setup-python@v5
+#         with:
+#           python-version: 3.11
 
-      - name: Install dependencies
-        run: |
-          pip install papermill==2.6.0 jupyter==1.1.1 ipykernel==6.29.5
-          pip install git+https://github.com/kubeflow/sdk.git@main
+#       - name: Install dependencies
+#         run: |
+#           pip install papermill==2.6.0 jupyter==1.1.1 ipykernel==6.29.5
+#           pip install git+https://github.com/kubeflow/sdk.git@main
 
-      - name: Setup cluster with GPU
-        run: |
-          make test-e2e-setup-gpu-cluster K8S_VERSION=${{ matrix.kubernetes-version }}
+#       - name: Setup cluster with GPU
+#         run: |
+#           make test-e2e-setup-gpu-cluster K8S_VERSION=${{ matrix.kubernetes-version }}
 
-      - name: Run e2e test on GPU cluster
-        run: |
-          mkdir -p artifacts/notebooks
-          make test-e2e-notebook NOTEBOOK_INPUT=./examples/torchtune/qwen2_5/qwen2.5-1.5B-with-alpaca.ipynb NOTEBOOK_OUTPUT=./artifacts/notebooks/${{ matrix.kubernetes-version }}_qwen2_5_with_alpaca-trainjob-yaml.ipynb TIMEOUT=900
+#       - name: Run e2e test on GPU cluster
+#         run: |
+#           mkdir -p artifacts/notebooks
+#           make test-e2e-notebook NOTEBOOK_INPUT=./examples/torchtune/qwen2_5/qwen2.5-1.5B-with-alpaca.ipynb NOTEBOOK_OUTPUT=./artifacts/notebooks/${{ matrix.kubernetes-version }}_qwen2_5_with_alpaca-trainjob-yaml.ipynb TIMEOUT=900
 
-      - name: Upload Artifacts to GitHub
-        if: always()
-        uses: actions/upload-artifact@v4
-        with:
-          name: ${{ matrix.kubernetes-version }}
-          path: ${{ env.GOPATH }}/src/github.com/kubeflow/trainer/artifacts/*
-          retention-days: 1
+#       - name: Upload Artifacts to GitHub
+#         if: always()
+#         uses: actions/upload-artifact@v4
+#         with:
+#           name: ${{ matrix.kubernetes-version }}
+#           path: ${{ env.GOPATH }}/src/github.com/kubeflow/trainer/artifacts/*
+#           retention-days: 1
 
-  delete-kind-cluster:
-    name: Delete kind Cluster
-    runs-on: arc-runner-set
-    needs: [gpu-e2e-test]
-    if: always()
-    steps:
-      - name: Delete any existing kind cluster
-        run: |
-          sudo kind delete cluster --name kind-gpu && echo "kind cluster has been deleted" || echo "kind cluster doesn't exist"
+#   delete-kind-cluster:
+#     name: Delete kind Cluster
+#     runs-on: arc-runner-set
+#     needs: [gpu-e2e-test]
+#     if: always()
+#     steps:
+#       - name: Delete any existing kind cluster
+#         run: |
+#           sudo kind delete cluster --name kind-gpu && echo "kind cluster has been deleted" || echo "kind cluster doesn't exist"
